### ISSUE TITLE
tata letak

### ISSUE THREAD

**Issue by firmannapi14** [firmannapi14/skripsi#3]
yan , atur tata letak ini tes yan..

![image](https://user-images.githubusercontent.com/41561941/43319704-e6d6aef2-91cf-11e8-8c93-d38f037f11f3.png)

**Comment by firmannapi14** [comment]
sama ini yan , sa kan pu database tentang input dicontoh ini ada, nah mahasiswa itu dia tetap input seperti ini sj yan, 

INPUT AWAL 
![image](https://user-images.githubusercontent.com/41561941/43320050-505d434e-91d1-11e8-8e08-4d1b9f58675f.png)

inpput hasil : 
[INPUT MAHASISWA]
![image](https://user-images.githubusercontent.com/41561941/43319817-5adb320a-91d0-11e8-9040-56238f4a2d47.png)
ket: field ambil dari database tb_sertifikat (sesuaikan dengan anjungan kolomnya)
[DATA AMBIL DARI DATABASE]
![image](https://user-images.githubusercontent.com/41561941/43319952-d4bc1d78-91d0-11e8-8830-0e0fa1a0603f.png)

KONFIRMASI AWAL
![image](https://user-images.githubusercontent.com/41561941/43320068-63fc1b46-91d1-11e8-8685-c0ddf7c10bed.png)

KONFIRMASI AKHIR
nanti da muncul seperti ini yan setelah proses, jadi apa yang da input itu nanti tertampung dulu
[KONFIRMASI MAHASISWA]
![image](https://user-images.githubusercontent.com/41561941/43319864-7d056486-91d0-11e8-8e21-a9f6aec5e75b.png)

Baru RESULTnya 
sudah betul yan, menampilkan 3 itu..
![image](https://user-images.githubusercontent.com/41561941/43320102-805a3dea-91d1-11e8-8ded-5bc1a055baa2.png)

SAMA DENGAN 

![image](https://user-images.githubusercontent.com/41561941/43320119-8f47084c-91d1-11e8-802d-dec22a297d44.png)

**Comment by pace11** [comment]
oke....

**Comment by firmannapi14** [comment]
yan ini yang lihat tong 2 sj to?

**Comment by pace11** [comment]
iyo.. cuman tong 2 saja..
aman wkwk
